Add files via upload
KelvinPompey-40718390/sem-project-group6 pull request #128
Opened 2024-04-10 08:37 UTC by Sekonyela1

2024-04-11 01:56 UTC, AntonJar-ENU commented on screenshots/UC1.png
Adjust Field Widths and put Headings in all CAPS  so that the Heading is distinguishable from the Data and makes better use of the Screen Space

2024-04-11 01:57 UTC, AntonJar-ENU commented on screenshots/UC2.png
The Report is asking for A Continent, Not all the Continents. 
Adjust so that the User can enter a Continent.

2024-04-11 01:58 UTC, AntonJar-ENU commented on screenshots/UC3.png
Region must be specified. 
Report Must have the headings as specified in the Assessment.
Code.
Name.
Continent.
Region.
Population.
Capital.

2024-04-11 02:04 UTC, AntonJar-ENU commented on screenshots/UC31.png
Report Requires additional Fields as outlined in the Assessment Guidelines:
The name of the continent/region/country.
The total population of the continent/region/country.
The total population of the continent/region/country living in cities (including a %).
The total population of the continent/region/country not living in cities (including a %).

In Addition it asks for the Population of A City. So the City should be entered by the End User.

2024-04-11 02:05 UTC, AntonJar-ENU commented on screenshots/UC4.png
Screenshot needs to show that the Number 6 was Entered.

2024-04-11 02:06 UTC, AntonJar-ENU requested changes
Reports are incomplete and do not return the Fields or show proof of Input by the End User.

2024-04-15 19:28 UTC, AntonJar-ENU submitted a review, later dismissed

2024-04-15 19:28 UTC, AntonJar-ENU approved these changes

2024-04-15 19:29 UTC, AntonJar-ENU approved these changes

2024-04-15 19:29 UTC, AntonJar-ENU approved these changes

2024-04-15 19:29 UTC, AntonJar-ENU approved these changes

2024-04-15 19:29 UTC, AntonJar-ENU approved these changes

2024-04-15 19:29 UTC, AntonJar-ENU approved these changes

2024-04-15 19:29 UTC, AntonJar-ENU approved these changes

2024-04-15 19:30 UTC, AntonJar-ENU approved these changes

2024-04-15 19:30 UTC, AntonJar-ENU approved these changes

2024-04-15 19:30 UTC, AntonJar-ENU approved these changes

2024-04-15 19:31 UTC, AntonJar-ENU approved these changes

2024-04-15 19:31 UTC, AntonJar-ENU approved these changes

2024-04-15 19:31 UTC, AntonJar-ENU approved these changes

2024-04-15 19:31 UTC, AntonJar-ENU approved these changes

2024-04-15 19:31 UTC, AntonJar-ENU approved these changes

2024-04-15 19:31 UTC, AntonJar-ENU approved these changes

2024-04-15 19:32 UTC, AntonJar-ENU approved these changes

2024-04-15 19:32 UTC, AntonJar-ENU approved these changes

2024-04-15 19:32 UTC, AntonJar-ENU approved these changes

2024-04-15 19:33 UTC, AntonJar-ENU approved these changes

2024-04-15 19:33 UTC, AntonJar-ENU submitted a review, later dismissed

2024-04-15 19:33 UTC, AntonJar-ENU submitted a review, later dismissed

2024-04-15 19:38 UTC, BobbyWal78 submitted a review, later dismissed
changes pending stiill, but will approve

2024-04-15 19:40 UTC, AntonJar-ENU approved these changes

2024-04-15 19:41 UTC, AntonJar-ENU approved these changes

2024-04-15 19:41 UTC, AntonJar-ENU reviewed
Looks workable

2024-04-15 19:41 UTC, AntonJar-ENU submitted a review, later dismissed
Good

2024-04-15 19:46 UTC, BobbyWal78 approved these changes
approved

2024-04-15 19:46 UTC, AntonJar-ENU submitted a review, later dismissed
Approved

2024-04-16 00:33 UTC, KelvinPompey-40718390 approved these changes

2024-04-16 00:37 UTC, AntonJar-ENU approved these changes

2024-04-16 00:39 UTC, KelvinPompey-40718390 approved these changes

2024-04-16 00:40 UTC, merged