feature/usc9
KelvinPompey-40718390/sem-project-group6 pull request #48
Opened 2024-02-09 23:59 UTC by BobbyWal78

2024-02-11 14:25 UTC, KelvinPompey-40718390 requested changes
@BobbyWal78 In the success scenarios I don't see where the user selects the region. Can you make that change? 

And we're leaving the diagrams for the next sprint. Can you remove it?

2024-02-12 23:47 UTC, BobbyWal78 commented
@KelvinPompey-40718390 digagram has been removed.

2024-02-12 23:48 UTC, BobbyWal78 reviewed
@KelvinPompey-40718390 digagram has been removed.

2024-02-13 17:41 UTC, KelvinPompey-40718390 approved these changes

2024-02-14 00:37 UTC, merged