Feature/uc1
KelvinPompey-40718390/sem-project-group6 pull request #66
Opened 2024-02-18 19:08 UTC by Sekonyela1

User Case 1 to 5 and 31 to 32

2024-02-18 21:49 UTC, AntonJar-ENU requested changes
Remove the Use Case Diagrams from the push both HR System.puml and use-cases.puml

2024-02-19 10:42 UTC, KelvinPompey-40718390 commented
@Sekonyela1 It appears that you've not removed the uml diagrams. I still see HR System.puml and use-cases.puml in the root directory.

2024-02-19 12:07 UTC, KelvinPompey-40718390 approved these changes

2024-02-19 17:49 UTC, AntonJar-ENU approved these changes

2024-02-20 06:22 UTC, merged